# Generated by Django 4.1.2 on 2022-10-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_postmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanager',
            name='status',
            field=models.CharField(choices=[('RJ', 'REJECT'), ('RJ', 'APPROVE'), ('W', 'Waiting')], default='Waiting', max_length=255),
        ),
    ]
