# Generated by Django 4.1.2 on 2022-10-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_alter_blogger_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blogger',
            field=models.BooleanField(blank=True, default=False, help_text='Can update posts', null=True),
        ),
    ]
